In [76]:
import numpy as np
from keras.preprocessing.text import one_hot
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras import layers 
from keras.layers import Embedding

In [77]:
reviews = ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement']

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [80]:
reviews[:5]

['nice food',
 'amazing restaurant',
 'too good',
 'just loved it!',
 'will go again']

In [81]:
sentiment[:5]

array([1, 1, 1, 1, 1])

In [82]:
one_hot('needs improvement', 50)

[36, 22]

In [83]:
vocabulary_size = 50

one_hot_reviews = [one_hot(review, vocabulary_size) for review in reviews]
one_hot_reviews

[[27, 42],
 [38, 32],
 [5, 5],
 [29, 29, 25],
 [14, 33, 10],
 [18, 42],
 [2, 33, 17],
 [15, 11],
 [15, 43],
 [36, 22]]

In [92]:
max_lenght = 3

padded_reviews = pad_sequences(one_hot_reviews, maxlen=max_lenght, padding='post')
padded_reviews

array([[27, 42,  0],
       [38, 32,  0],
       [ 5,  5,  0],
       [29, 29, 25],
       [14, 33, 10],
       [18, 42,  0],
       [ 2, 33, 17],
       [15, 11,  0],
       [15, 43,  0],
       [36, 22,  0]], dtype=int32)

In [94]:
x = padded_reviews
y = sentiment

In [93]:
embedding_feature_size = 4

model = Sequential()
model.add(Embedding(
    vocabulary_size, 
    embedding_feature_size, 
    input_length=max_lenght, 
    name='embedding'
    ))

model.add(layers.Flatten())
model.add(layers.Dense(units=1, activation='sigmoid'))
model.summary()

Model: "sequential_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 3, 4)              200       
_________________________________________________________________
flatten_4 (Flatten)          (None, 12)                0         
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 13        
Total params: 213
Trainable params: 213
Non-trainable params: 0
_________________________________________________________________


In [100]:
model.compile(
    optimizer='adam', 
    loss='binary_crossentropy', 
    metrics=['acc']
    )

model.fit(
    x, 
    y, 
    epochs=20, 
    verbose=0
    )

In [101]:
loss, accuracy = model.evaluate(x, y)
loss, accuracy

1/1 [==============================] - 0s 100ms/step - loss: 0.5685 - acc: 1.0000


(0.5684901475906372, 1.0)

In [102]:
model.get_layer('embedding').get_weights()[0]

array([[ 5.77073954e-02,  1.39195099e-01, -7.38048702e-02,
        -1.07936338e-01],
       [ 4.26434390e-02,  1.39576532e-02,  8.22987407e-03,
        -3.68744135e-03],
       [-8.39819983e-02,  1.34202838e-01, -9.53623131e-02,
         7.85126835e-02],
       [ 4.94719259e-02, -2.51257177e-02, -4.95472662e-02,
        -2.48840209e-02],
       [ 3.30007412e-02, -1.72408111e-02, -1.74011588e-02,
         2.77758576e-02],
       [-1.30432680e-01, -7.16282949e-02,  7.42950961e-02,
        -8.40196535e-02],
       [ 2.95908786e-02, -4.31770198e-02, -2.96194479e-03,
        -1.56788230e-02],
       [ 4.31490280e-02, -4.89254706e-02,  6.48493692e-03,
         1.96432732e-02],
       [ 1.25122331e-02, -3.67064960e-02,  3.42784859e-02,
         1.81068443e-02],
       [-9.38899443e-03,  1.50947832e-02,  4.85807657e-03,
        -2.14596875e-02],
       [-1.33791104e-01, -1.09772503e-01,  1.28329933e-01,
         9.73426625e-02],
       [ 7.23486319e-02, -1.37993649e-01, -1.22622557e-01,
      

In [104]:
weights = model.get_layer('embedding').get_weights()[0]
weights[:5]

array([[ 0.0577074 ,  0.1391951 , -0.07380487, -0.10793634],
       [ 0.04264344,  0.01395765,  0.00822987, -0.00368744],
       [-0.083982  ,  0.13420284, -0.09536231,  0.07851268],
       [ 0.04947193, -0.02512572, -0.04954727, -0.02488402],
       [ 0.03300074, -0.01724081, -0.01740116,  0.02777586]],
      dtype=float32)

In [105]:
weights[27]

array([ 0.12811516, -0.12460197,  0.13071296, -0.11221685], dtype=float32)

In [106]:
weights[5]

array([-0.13043268, -0.07162829,  0.0742951 , -0.08401965], dtype=float32)